run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - vendor
    - node_modules
  skip-files:
    - ".*_test.go"

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - gocognit
    - godot
    - godox
    - goerr113
    - nestif
    - prealloc
    - testpackage
    - revive
    - wsl

  disable:
    - maligned
    - gochecknoglobals

linters-settings:
  dupl:
    threshold: 100
  
  funlen:
    lines: 100
    statements: 50
  
  gci:
    local-prefixes: github.com/vaultenv/vaultenv-cli
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  
  gocyclo:
    min-complexity: 15
  
  goimports:
    local-prefixes: github.com/vaultenv/vaultenv-cli
  
  golint:
    min-confidence: 0
  
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,return
  
  govet:
    check-shadowing: true
  
  lll:
    line-length: 140
  
  misspell:
    locale: US
  
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
  
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  gosec:
    excludes:
      - G101 # Potential hardcoded credentials
      - G304 # Potential file inclusion via variable
  
  nestif:
    min-complexity: 4
  
  godot:
    scope: declarations
    capital: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - dupl
        - gosec
    
    - path: cmd/
      linters:
        - gochecknoinits
    
    - path: internal/cmd/
      linters:
        - funlen
    
    - linters:
        - lll
      source: "^//go:generate "