# .goreleaser.yml
version: 2

project_name: vaultenv-cli

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: vaultenv-cli
    main: ./cmd/vaultenv-cli
    binary: vaultenv-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}
      - -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: vaultenv-cli
    builds:
      - vaultenv-cli
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md
      - docs/*
      - src: CHANGELOG.md
        dst: CHANGELOG.md
        strip_parent: false

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Documentation
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: vaultenv
    name: vaultenv-cli
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## VaultEnv CLI v{{.Version}}

    Welcome to the {{ if .IsSnapshot }}snapshot{{ else }}{{ if .Prerelease }}pre-release{{ else }}release{{ end }}{{ end }} of VaultEnv CLI!

    ### Installation

    #### Quick Install (Linux/macOS)
    ```bash
    curl -sSL https://raw.githubusercontent.com/vaultenv/vaultenv-cli/main/install.sh | bash
    ```

    #### Manual Download
    Download the appropriate archive for your platform below.

  footer: |
    ## What's Next?

    - Read the [documentation](https://github.com/vaultenv/vaultenv-cli#readme)
    - Report issues at [GitHub Issues](https://github.com/vaultenv/vaultenv-cli/issues)
    - Join our [community discussions](https://github.com/vaultenv/vaultenv-cli/discussions)

    **Full Changelog**: https://github.com/vaultenv/vaultenv-cli/compare/{{ .PreviousTag }}...{{ .Tag }}

# Optional: Linux packages
nfpms:
  - id: vaultenv-cli
    package_name: vaultenv-cli
    builds:
      - vaultenv-cli
    vendor: VaultEnv
    homepage: https://github.com/vaultenv/vaultenv-cli
    maintainer: VaultEnv Team <gnana097@gmail.com>
    description: Secure environment variable management for modern teams
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/vaultenv-cli/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/vaultenv-cli/README.md
    overrides:
      deb:
        dependencies:
          - ca-certificates
      rpm:
        dependencies:
          - ca-certificates
